In [1]:
import sympy as sp

# Variables simbólicas
t = sp.Symbol('t')
x = sp.Symbol('x')
h = sp.Symbol('h')

# Valores de la función
u0, u1, u2 = sp.symbols('u0 u1 u2')

# Nodos
x0 = x - 2*h
x1 = x - h
x2 = x

# Polinomios de Lagrange
L0 = ((t-x1)*(t-x2))/((x0-x1)*(x0-x2))
L1 = ((t-x0)*(t-x2))/((x1-x0)*(x1-x2))
L2 = ((t-x0)*(t-x1))/((x2-x0)*(x2-x1))

# Polinomio interpolador
p = u0*L0 + u1*L1 + u2*L2

print("Polinomio interpolador:")
print(sp.expand(p))

Polinomio interpolador:
u2 + t*u0/(2*h) - 2*t*u1/h + 3*t*u2/(2*h) - u0*x/(2*h) + 2*u1*x/h - 3*u2*x/(2*h) + t**2*u0/(2*h**2) - t**2*u1/h**2 + t**2*u2/(2*h**2) - t*u0*x/h**2 + 2*t*u1*x/h**2 - t*u2*x/h**2 + u0*x**2/(2*h**2) - u1*x**2/h**2 + u2*x**2/(2*h**2)


u(x−2h)=u_0
	​


u(x−h)=u_1
	​


u(x)=u_2
	​



In [2]:
dp = sp.diff(p,t)

formula = sp.simplify(dp.subs(t,x))

print(formula)

(u0 - 4*u1 + 3*u2)/(2*h)


In [3]:
u = sp.Function('u')

expr = (u(x-2*h) - 4*u(x-h) + 3*u(x))/(2*h)

serie = sp.series(expr, h, 0, 5)

print(serie)

Subs(Derivative(u(_xi_1), _xi_1), _xi_1, x) - h**2*Subs(Derivative(u(_xi_1), (_xi_1, 3)), _xi_1, x)/3 + h**3*Subs(Derivative(u(_xi_1), (_xi_1, 4)), _xi_1, x)/4 - 7*h**4*Subs(Derivative(u(_xi_1), (_xi_1, 5)), _xi_1, x)/60 + O(h**5)


In [4]:
import sympy as sp

t = sp.Symbol('t')
x = sp.Symbol('x')
h = sp.Symbol('h')

u0,u1,u2,u3,u4 = sp.symbols('u0:5')

nodes = [
    x-2*h,
    x-h,
    x,
    x+h,
    x+2*h
]

values = [u0,u1,u2,u3,u4]

p = 0

for i in range(5):

    Li = 1

    for j in range(5):

        if i != j:
            Li *= (t-nodes[j])/(nodes[i]-nodes[j])

    p += values[i]*Li

p = sp.simplify(p)

dp = sp.diff(p,t)

formula = sp.simplify(dp.subs(t,x))

print(formula)

(u0 - 8*u1 + 8*u3 - u4)/(12*h)


In [5]:
u = sp.Function('u')

expr = (
    u(x-2*h)
    -8*u(x-h)
    +8*u(x+h)
    -u(x+2*h)
)/(12*h)

serie = sp.series(expr,h,0,7)

print(serie)

Subs(Derivative(u(_xi_1), _xi_1), _xi_1, x) - h**4*Subs(Derivative(u(_xi_1), (_xi_1, 5)), _xi_1, x)/30 - h**6*Subs(Derivative(u(_xi_1), (_xi_1, 7)), _xi_1, x)/252 + O(h**7)


In [6]:
import numpy as np

def D_backward_O2(n, h):
    """
    Matriz de diferenciación backward de orden 2
    con condiciones periódicas.

    Aproxima:

    u'(x_i) ≈ (u_{i-2} - 4u_{i-1} + 3u_i)/(2h)

    Parámetros
    ----------
    n : int
        Cantidad de nodos.
    h : float
        Paso de la grilla.

    Retorna
    -------
    D : ndarray (n x n)
        Matriz de diferenciación.
    """

    D = np.zeros((n, n))

    for i in range(n):

        # coeficiente de u_i
        D[i, i] = 3

        # coeficiente de u_{i-1}
        D[i, (i-1) % n] = -4

        # coeficiente de u_{i-2}
        D[i, (i-2) % n] = 1

    return D / (2*h)

In [7]:
n = 5
h = 0.2

D = D_backward_O2(n, h)

print(D)

[[  7.5   0.    0.    2.5 -10. ]
 [-10.    7.5   0.    0.    2.5]
 [  2.5 -10.    7.5   0.    0. ]
 [  0.    2.5 -10.    7.5   0. ]
 [  0.    0.    2.5 -10.    7.5]]


In [8]:
import numpy as np

def D_centered_O4(n, h):
    """
    Matriz de diferenciación centrada de orden 4
    con condiciones periódicas.

    Aproxima:

    u'(x_i) ≈
    (u_{i-2} - 8u_{i-1}
     + 8u_{i+1} - u_{i+2})/(12h)

    Parámetros
    ----------
    n : int
        Cantidad de nodos.
    h : float
        Paso de la grilla.

    Retorna
    -------
    D : ndarray (n x n)
        Matriz de diferenciación.
    """

    D = np.zeros((n, n))

    for i in range(n):

        # u_{i-2}
        D[i, (i-2) % n] = 1

        # u_{i-1}
        D[i, (i-1) % n] = -8

        # u_{i+1}
        D[i, (i+1) % n] = 8

        # u_{i+2}
        D[i, (i+2) % n] = -1

    return D / (12*h)

In [9]:
n = 5
h = 0.2

D = D_centered_O4(n, h)

print(D)

[[ 0.          3.33333333 -0.41666667  0.41666667 -3.33333333]
 [-3.33333333  0.          3.33333333 -0.41666667  0.41666667]
 [ 0.41666667 -3.33333333  0.          3.33333333 -0.41666667]
 [-0.41666667  0.41666667 -3.33333333  0.          3.33333333]
 [ 3.33333333 -0.41666667  0.41666667 -3.33333333  0.        ]]


In [10]:
n = 100

x = np.linspace(0, 1, n, endpoint=False)
h = x[1] - x[0]

u = np.sin(2*np.pi*x)

du_exacta = 2*np.pi*np.cos(2*np.pi*x)

D = D_centered_O4(n, h)

du_num = D @ u

error = np.max(np.abs(du_num - du_exacta))

print("Error =", error)

Error = 3.262676216309046e-06
